### ISSUE TITLE
TODO: Doc updates before 2.0.0 release

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#170]
- [x] - Comb through plunkers I've made, clean up their titles/descriptions and add them to an "Examples" page
- [x] - Events, especially "change" events
- [x] - `returnMeta`
- [x] - Relation changes (property accessors)
- [x] - Default values
- [x] - `DS#refreshAll`
- [x] - `onConflict: 'replace'`
- [x] - `omit`
- [x] - AOP
- [x] - Collections
- [x] - Filtering by nested fields
- [x] - `Promise` not included anymore
- [x] - Coupling with js-data-schema removed
- [x] - Actions
