### ISSUE TITLE
v3 Release Checklist

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data#435]
## Docs

- [ ] Tutorial: Relations
- [ ] Tutorial: Working with the DataStore
- [ ] Guides: Using JSData in the Browser
- [ ] APIS & Reference: Events & Listeners
- [ ] Guides: Migrating to v3

**Comment by jmdobry** [comment]
Finished [Tutorial: Relations](http://www.js-data.io/v3.0/docs/relations), anyone care to review?

**Comment by jmdobry** [comment]
Finished [Tutorial: Working with the DataStore](http://www.js-data.io/v3.0/docs/working-with-the-datastore), anyone care to review?

**Comment by Goopil** [comment]
There seems to be no reference about parent: true (nested rest endpoint) in the relationship section. Has this feature been deprecated

**Comment by jmdobry** [comment]
`parent: true` is specific to the http adapter, documentation for that should probably go here: http://www.js-data.io/v3.0/docs/js-data-http

**Comment by jmdobry** [comment]
Finished http://www.js-data.io/v3.0/docs/glossary, http://www.js-data.io/v3.0/docs/events, and http://www.js-data.io/v3.0/docs/tracking-changes. Thanks for your help @crobinson42

**Comment by jmdobry** [comment]
Anyone want to review and suggest changes to the v3 migration guide before I proceed with publishing v3 stable? http://www.js-data.io/v3.0/docs/migrating-to-v3
